In [3]:
import pandas as pd
import numpy as np

In [4]:
import warnings
warnings.filterwarnings('ignore')
pd.set_option('max_column',None)
df = pd.read_excel('../data/Week1_challenge_data_source.xlsx')
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [12]:
#Display all column names
df.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

# Handling Missing Values

In [16]:
#Total number of data
print(f'There are {df.shape[0]} rows and {df.shape[1]} columns')

There are 150001 rows and 55 columns

In [17]:
#Function to calculate percentage of missing values
def percent_missing(df):
    
    #Calculate total number of cells
    totalCells = np.product(df.shape)
    
    #Count number of missing values per column
    missingCount = df.isnull().sum()
    
    #Calculate total number of missing values
    totalMissing = missingCount.sum()
    
    #Calculate percentage of missing values
    print("The telecom datasets contains", round(((totalMissing/totalCells)*100),2),"%","missing values")
    
percent_missing(df)

The telecom datasets contains 12.5 % missing values

In [19]:
# Missing value amount of each column
df.isna().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [22]:
# Drop columns with more than 80% missing values
limitPer = len(df) * .80
df_clean = df.dropna(thresh=limitPer, axis=1)
df_clean.isna().sum()

Bearer Id                           991
Start                                 1
Start ms                              1
End                                   1
End ms                                1
Dur. (ms)                             1
IMSI                                570
MSISDN/Number                      1066
IMEI                                572
Last Location Name                 1153
Avg RTT DL (ms)                   27829
Avg RTT UL (ms)                   27812
Avg Bearer TP DL (kbps)               1
Avg Bearer TP UL (kbps)               1
DL TP < 50 Kbps (%)                 754
50 Kbps < DL TP < 250 Kbps (%)      754
250 Kbps < DL TP < 1 Mbps (%)       754
DL TP > 1 Mbps (%)                  754
UL TP < 10 Kbps (%)                 792
10 Kbps < UL TP < 50 Kbps (%)       792
50 Kbps < UL TP < 300 Kbps (%)      792
UL TP > 300 Kbps (%)                792
Activity Duration DL (ms)             1
Activity Duration UL (ms)             1
Dur. (ms).1                           1
Handset Manufacturer                572
Handset Type                        572
Nb of sec with Vol DL < 6250B       755
Nb of sec with Vol UL < 1250B       793
Social Media DL (Bytes)               0
Social Media UL (Bytes)               0
Google DL (Bytes)                     0
Google UL (Bytes)                     0
Email DL (Bytes)                      0
Email UL (Bytes)                      0
Youtube DL (Bytes)                    0
Youtube UL (Bytes)                    0
Netflix DL (Bytes)                    0
Netflix UL (Bytes)                    0
Gaming DL (Bytes)                     0
Gaming UL (Bytes)                     0
Other DL (Bytes)                      0
Other UL (Bytes)                      0
Total UL (Bytes)                      1
Total DL (Bytes)                      1
dtype: int64

In [23]:
features_to_not_be_null = ['Start', 'IMEI', 'IMSI','MSISDN/Number']
for feature in features_to_not_be_null:
  df_clean = df_clean[df_clean[feature].notnull()]

In [30]:
df_clean.isnull().sum()

Bearer Id                           429
Start                                 0
Start ms                              0
End                                   0
End ms                                0
Dur. (ms)                             0
IMSI                                  0
MSISDN/Number                         0
IMEI                                  0
Last Location Name                  589
Avg RTT DL (ms)                   27644
Avg RTT UL (ms)                   27625
Avg Bearer TP DL (kbps)               0
Avg Bearer TP UL (kbps)               0
DL TP < 50 Kbps (%)                 720
50 Kbps < DL TP < 250 Kbps (%)      720
250 Kbps < DL TP < 1 Mbps (%)       720
DL TP > 1 Mbps (%)                  720
UL TP < 10 Kbps (%)                 767
10 Kbps < UL TP < 50 Kbps (%)       767
50 Kbps < UL TP < 300 Kbps (%)      767
UL TP > 300 Kbps (%)                767
Activity Duration DL (ms)             0
Activity Duration UL (ms)             0
Dur. (ms).1                           0
Handset Manufacturer                  0
Handset Type                          0
Nb of sec with Vol DL < 6250B       721
Nb of sec with Vol UL < 1250B       768
Social Media DL (Bytes)               0
Social Media UL (Bytes)               0
Google DL (Bytes)                     0
Google UL (Bytes)                     0
Email DL (Bytes)                      0
Email UL (Bytes)                      0
Youtube DL (Bytes)                    0
Youtube UL (Bytes)                    0
Netflix DL (Bytes)                    0
Netflix UL (Bytes)                    0
Gaming DL (Bytes)                     0
Gaming UL (Bytes)                     0
Other DL (Bytes)                      0
Other UL (Bytes)                      0
Total UL (Bytes)                      0
Total DL (Bytes)                      0
dtype: int64

In [24]:
# fill missing with ffill method for 

def fix_missing_ffill(df, col):
    df[col] = df[col].fillna(method='ffill')
    return df[col]

def fix_missing_bfill(df, col):
    df[col] = df[col].fillna(method='bfill')
    return df[col]

def fix_missing_mean(df, col):
    df[col] = df[col].fillna(df[col].mean())
    return df[col]

def fix_missing_median(df, col):
    df[col] = df[col].fillna(df[col].median())  
    return df[col]

def fix_missing_mode(df, col):
    df[col] = df[col].fillna(df_clean[col].mode()[0])
    return df[col]

In [25]:
df_clean['MSISDN/Number'] = fix_missing_ffill(df_clean, 'MSISDN/Number')
df_clean['Handset Type'] = fix_missing_ffill(df_clean, 'Handset Type')
df_clean['Handset Manufacturer'] = fix_missing_ffill(df_clean, 'Handset Manufacturer')
df_clean['IMSI'] = fix_missing_ffill(df_clean, 'IMSI')


df_clean["Last Location Name"] = fix_missing_mode(df_clean,"Last Location Name")
missing_columns = ["Bearer Id",
                   "Avg RTT DL (ms)",
                   "Avg RTT UL (ms)",
                   "DL TP < 50 Kbps (%)",
                   "50 Kbps < DL TP < 250 Kbps (%)",
                   "250 Kbps < DL TP < 1 Mbps (%)",
                   "DL TP > 1 Mbps (%)",
                   "UL TP < 10 Kbps (%)",
                   "10 Kbps < UL TP < 50 Kbps (%)",
                   "50 Kbps < UL TP < 300 Kbps (%)",
                   "UL TP > 300 Kbps (%)",
                   "Nb of sec with Vol DL < 6250B",
                   "Nb of sec with Vol UL < 1250B"]

for i in missing_columns:
    df_clean[i] = fix_missing_median(df_clean, i)

In [26]:
df_clean.isna().sum()
# df_clean.dtypes

Bearer Id                         0
Start                             0
Start ms                          0
End                               0
End ms                            0
Dur. (ms)                         0
IMSI                              0
MSISDN/Number                     0
IMEI                              0
Last Location Name                0
Avg RTT DL (ms)                   0
Avg RTT UL (ms)                   0
Avg Bearer TP DL (kbps)           0
Avg Bearer TP UL (kbps)           0
DL TP < 50 Kbps (%)               0
50 Kbps < DL TP < 250 Kbps (%)    0
250 Kbps < DL TP < 1 Mbps (%)     0
DL TP > 1 Mbps (%)                0
UL TP < 10 Kbps (%)               0
10 Kbps < UL TP < 50 Kbps (%)     0
50 Kbps < UL TP < 300 Kbps (%)    0
UL TP > 300 Kbps (%)              0
Activity Duration DL (ms)         0
Activity Duration UL (ms)         0
Dur. (ms).1                       0
Handset Manufacturer              0
Handset Type                      0
Nb of sec with Vol DL < 6250B     0
Nb of sec with Vol UL < 1250B     0
Social Media DL (Bytes)           0
Social Media UL (Bytes)           0
Google DL (Bytes)                 0
Google UL (Bytes)                 0
Email DL (Bytes)                  0
Email UL (Bytes)                  0
Youtube DL (Bytes)                0
Youtube UL (Bytes)                0
Netflix DL (Bytes)                0
Netflix UL (Bytes)                0
Gaming DL (Bytes)                 0
Gaming UL (Bytes)                 0
Other DL (Bytes)                  0
Other UL (Bytes)                  0
Total UL (Bytes)                  0
Total DL (Bytes)                  0
dtype: int64

In [27]:
df_clean.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.489350e+05,148935.000000,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,148935.000000,148935.000000,1.489350e+05,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05
mean,1.013870e+19,499.246732,498.675442,1.048702e+05,2.082016e+14,4.188282e+10,4.849493e+13,96.489522,15.293235,13286.171390,1770.786497,92.898889,3.043106,1.705449,1.600141,98.540330,0.771363,0.147219,0.078739,1.834542e+06,1.412540e+06,1.048707e+08,3710.978642,4009.586316,1.795161e+06,32921.716077,5.751574e+06,2.056217e+06,1.791769e+06,467389.473824,1.163345e+07,1.100867e+07,1.162756e+07,1.100017e+07,4.220256e+08,8.289085e+06,4.211473e+08,8.263189e+06,4.111764e+07,4.546251e+08
std,2.892977e+18,288.555630,288.089136,8.106343e+04,1.522166e+10,2.447443e+12,2.242829e+13,536.879667,76.683630,23978.591234,4629.475837,13.006268,6.195882,4.149469,4.811365,4.626944,3.216333,1.623262,1.295662,5.710293e+06,4.655541e+06,8.106342e+07,9171.884935,10157.312209,1.035458e+06,19006.779115,3.309041e+06,1.189936e+06,1.035910e+06,269974.713258,6.711384e+06,6.345428e+06,6.724686e+06,6.358918e+06,2.439763e+08,4.782090e+06,2.431970e+08,4.768708e+06,1.127933e+07,2.441528e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,7.142988e+06,1.000000,1.000000,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,1.400000e+01,2.000000,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.788350e+04,2.082014e+14,3.365130e+10,3.546071e+13,35.000000,3.000000,43.000000,47.000000,91.000000,0.000000,0.000000,0.000000,99.000000,0.000000,0.000000,0.000000,1.488500e+04,2.154800e+04,5.788424e+07,88.000000,106.000000,8.989585e+05,16438.000000,2.882538e+06,1.023948e+06,8.926520e+05,233424.000000,5.831331e+06,5.516710e+06,5.779947e+06,5.474451e+06,2.104587e+08,4.130162e+06,2.102119e+08,4.145072e+06,3.321774e+07,2.430996e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572221e+13,45.000000,5.000000,63.000000,63.000000,100.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,3.916100e+04,4.663100e+04,8.639998e+07,202.000000,216.000000,1.793766e+06,32914.000000,5.767387e+06,2.053879e+06,1.793585e+06,466357.000000,1.161638e+07,1.101329e+07,1.164269e+07,1.099563e+07,4.234208e+08,8.291222e+06,4.218716e+08,8.266089e+06,4.114101e+07,4.558708e+08
75%,1.304243e+19,749.000000,750.000000,1.327000e+05,2.082018e+14,3.368349e+10,8.611970e+13,62.000000,11.000000,19681.000000,1117.000000,100.000000,4.000000,1.000000,0.000000,100.000000,0.000000,0.000000,0.000000,6.779400e+05,5.961860e+05,1.327006e+08,2609.000000,2409.000000,2.694884e+06,49327.000000,8.624448e+06,3.088343e+06,2.689637e+06,700443.000000,1.744571e+07,1.651442e+07,1.747072e+07,1.650429e+07,6.331620e+08,1.243184e+07,6.316602e+08,1.238204e+07,4.903248e+07,6.656577e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.082522e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,58613.000000,100.000000,93.000000,100.000000,94.000000,100.000000,98.000000,100.000000,96.000000,1.365365e+08,1.449113e+08,1.859336e+09,604061.000000,604122.000000,3.586064e+06,65870.000000,1.146283e+07,4.121357e+06,3.586146e+06,936418.000000,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

# Check for timeliness of the data

In [28]:
df_clean.dtypes
df_clean.index = pd.to_datetime(df_clean.index)
# df_clean.index.to_pydatetime()
df_clean['difference'] = (df_clean['End']- df_clean['Start'])

df_clean['difference']

1970-01-01 00:00:00.000000000   21 days 02:34:13
1970-01-01 00:00:00.000000001   15 days 19:11:44
1970-01-01 00:00:00.000000002   15 days 18:16:02
1970-01-01 00:00:00.000000003   15 days 07:05:10
1970-01-01 00:00:00.000000004   12 days 14:30:09
                                      ...
1970-01-01 00:00:00.000149995    0 days 16:33:08
1970-01-01 00:00:00.000149996    0 days 22:33:51
1970-01-01 00:00:00.000149997    1 days 03:12:51
1970-01-01 00:00:00.000149998    1 days 03:17:29
1970-01-01 00:00:00.000149999    1 days 03:11:51
Name: difference, Length: 148935, dtype: timedelta64[ns]

In [29]:
df_clean[:30]['difference'] / np.timedelta64(1, 's')

1970-01-01 00:00:00.000000000    1823653.0
1970-01-01 00:00:00.000000001    1365104.0
1970-01-01 00:00:00.000000002    1361762.0
1970-01-01 00:00:00.000000003    1321510.0
1970-01-01 00:00:00.000000004    1089009.0
1970-01-01 00:00:00.000000005    1074638.0
1970-01-01 00:00:00.000000006    1035262.0
1970-01-01 00:00:00.000000007     951293.0
1970-01-01 00:00:00.000000008     941634.0
1970-01-01 00:00:00.000000009     864482.0
1970-01-01 00:00:00.000000010     848637.0
1970-01-01 00:00:00.000000011     889835.0
1970-01-01 00:00:00.000000012     850766.0
1970-01-01 00:00:00.000000013     812508.0
1970-01-01 00:00:00.000000014     777888.0
1970-01-01 00:00:00.000000015     780471.0
1970-01-01 00:00:00.000000016     767722.0
1970-01-01 00:00:00.000000017     780991.0
1970-01-01 00:00:00.000000018     778387.0
1970-01-01 00:00:00.000000019     772583.0
1970-01-01 00:00:00.000000020     706649.0
1970-01-01 00:00:00.000000021     691484.0
1970-01-01 00:00:00.000000022     723714.0
1970-01-01 00:00:00.000000023     686791.0
1970-01-01 00:00:00.000000024     711485.0
1970-01-01 00:00:00.000000025     652176.0
1970-01-01 00:00:00.000000026     716505.0
1970-01-01 00:00:00.000000027     702570.0
1970-01-01 00:00:00.000000028     695346.0
1970-01-01 00:00:00.000000029     682927.0
Name: difference, dtype: float64

In [30]:
type(df_clean[:30]['difference'] / np.timedelta64(1, 's'))
s = df_clean['difference'] / np.timedelta64(1, 's')
df_clean['duration'] = df_clean['difference'] / np.timedelta64(1, 's')
s.sum()

15618918979.0

In [31]:
df_clean.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes),difference,duration
count,1.489350e+05,148935.000000,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,148935.000000,148935.000000,1.489350e+05,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,148935.000000,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,1.489350e+05,148935,1.489350e+05
mean,1.013870e+19,499.246732,498.675442,1.048702e+05,2.082016e+14,4.188282e+10,4.849493e+13,96.489522,15.293235,13286.171390,1770.786497,92.898889,3.043106,1.705449,1.600141,98.540330,0.771363,0.147219,0.078739,1.834542e+06,1.412540e+06,1.048707e+08,3710.978642,4009.586316,1.795161e+06,32921.716077,5.751574e+06,2.056217e+06,1.791769e+06,467389.473824,1.163345e+07,1.100867e+07,1.162756e+07,1.100017e+07,4.220256e+08,8.289085e+06,4.211473e+08,8.263189e+06,4.111764e+07,4.546251e+08,1 days 05:07:50.708557424,1.048707e+05
std,2.892977e+18,288.555630,288.089136,8.106343e+04,1.522166e+10,2.447443e+12,2.242829e+13,536.879667,76.683630,23978.591234,4629.475837,13.006268,6.195882,4.149469,4.811365,4.626944,3.216333,1.623262,1.295662,5.710293e+06,4.655541e+06,8.106342e+07,9171.884935,10157.312209,1.035458e+06,19006.779115,3.309041e+06,1.189936e+06,1.035910e+06,269974.713258,6.711384e+06,6.345428e+06,6.724686e+06,6.358918e+06,2.439763e+08,4.782090e+06,2.431970e+08,4.768708e+06,1.127933e+07,2.441528e+08,0 days 22:31:03.419319362,8.106342e+04
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,7.142988e+06,1.000000,1.000000,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,1.400000e+01,2.000000,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06,0 days 01:59:03,7.143000e+03
25%,7.349883e+18,250.000000,251.000000,5.788350e+04,2.082014e+14,3.365130e+10,3.546071e+13,35.000000,3.000000,43.000000,47.000000,91.000000,0.000000,0.000000,0.000000,99.000000,0.000000,0.000000,0.000000,1.488500e+04,2.154800e+04,5.788424e+07,88.000000,106.000000,8.989585e+05,16438.000000,2.882538e+06,1.023948e+06,8.926520e+05,233424.000000,5.831331e+06,5.516710e+06,5.779947e+06,5.474451e+06,2.104587e+08,4.130162e+06,2.102119e+08,4.145072e+06,3.321774e+07,2.430996e+08,0 days 16:04:44,5.788400e+04
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572221e+13,45.000000,5.000000,63.000000,63.000000,100.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,3.916100e+04,4.663100e+04,8.639998e+07,202.000000,216.000000,1.793766e+06,32914.000000,5.767387e+06,2.053879e+06,1.793585e+06,466357.000000,1.161638e+07,1.101329e+07,1.164269e+07,1.099563e+07,4.234208e+08,8.291222e+06,4.218716e+08,8.266089e+06,4.114101e+07,4.558708e+08,1 days 00:00:00,8.640000e+04
75%,1.304243e+19,749.000000,750.000000,1.327000e+05,2.082018e+14,3.368349e+10,8.611970e+13,62.000000,11.000000,19681.000000,1117.000000,100.000000,4.000000,1.000000,0.000000,100.000000,0.000000,0.000000,0.000000,6.779400e+05,5.961860e+05,1.327006e+08,2609.000000,2409.000000,2.694884e+06,49327.000000,8.624448e+06,3.088343e+06,2.689637e+06,700443.000000,1.744571e+07,1.651442e+07,1.747072e+07,1.650429e+07,6.331620e+08,1.243184e+07,6.316602e+08,1.238204e+07,4.903248e+07,6.656577e+08,1 days 12:51:40.500000,1.327005e+05
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.082522e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,58613.000000,100.000000,93.000000,100.000000,94.000000,100.000000,98.000000,100.000000,96.000000,1.365365e+08,1.449113e+08,1.859336e+09,604061.000000,604122.000000,3.586064e+06,65870.000000,1.146283e+07,4.121357e+06,3.586146e+06,936418.000000,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08,21 days 12:28:57,1.859337e+06

In [32]:
# Function to calculate missing values by column
def missing_values_table(df):
    # Total missing values
    mis_val = df.isnull().sum()

    # Percentage of missing values
    mis_val_percent = 100 * df.isnull().sum() / len(df)

    # dtype of missing values
    mis_val_dtype = df.dtypes

    # Make a table with the results
    mis_val_table = pd.concat([mis_val, mis_val_percent, mis_val_dtype], axis=1)

    # Rename the columns
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values', 2: 'Dtype'})

    # Sort the table by percentage of missing descending
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)

    # Print some summary information
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
        "There are " + str(mis_val_table_ren_columns.shape[0]) +
          " columns that have missing values.")

    # Return the dataframe with missing information
    return mis_val_table_ren_columns

def format_float(value):
    return f'{value:,.2f}'

def find_agg(df:pd.DataFrame, agg_column:str, agg_metric:str, col_name:str, top:int, order=False )->pd.DataFrame:
    
    new_df = df.groupby(agg_column)[agg_column].agg(agg_metric).reset_index(name=col_name).\
                        sort_values(by=col_name, ascending=order)[:top]
    
    return new_df

def convert_bytes_to_megabytes(df, bytes_data):
    """
        This function takes the dataframe and the column which has the bytes values
        returns the megabytesof that value
        
        Args:
        -----
        df: dataframe
        bytes_data: column with bytes values
        
        Returns:
        --------
        A series
    """
    
    megabyte = 1*10e+5
    df[bytes_data] = df[bytes_data] / megabyte
    
    return df[bytes_data]

pd.options.display.float_format = format_float

In [33]:
#deleting the suffix (Bytes) after each word

byte_columns = [ 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

for col in byte_columns:
  print(col[:-8])

Social Media DL
Social Media UL
Google DL
Google UL
Email DL
Email UL
Youtube DL
Youtube UL
Netflix DL
Netflix UL
Gaming DL
Gaming UL
Other DL
Other UL
Total UL
Total DL

In [34]:
# Renaming the byte suffix columns

for col in byte_columns:
  df_clean.rename(columns={col:col[:-8]}, inplace=True)

In [35]:
Users = df_clean.groupby(['IMSI'])

In [36]:
xDR_users = df_clean['IMSI'].value_counts()
session_duration = Users['Dur. (ms)'].sum()
Total_session_UL = Users['Total UL'].sum()
Total_session_DL = Users['Total DL'].sum()
Total_session_mb = Users['Total DL'].sum() + Users['Total UL'].sum()
Total_Social_mb = Users['Social Media DL'].sum() + Users['Social Media UL'].sum()
Total_Google_mb = Users['Google DL'].sum() + Users['Google UL'].sum()
Total_Email_mb= Users['Email DL'].sum() + Users['Email UL'].sum()
Total_Youtube_mb = Users['Youtube DL'].sum() + Users['Youtube UL'].sum()
Total_Netflix_mb = Users['Netflix DL'].sum() + Users['Netflix UL'].sum()
Total_Gaming_mb = Users['Gaming DL'].sum() + Users['Gaming UL'].sum()
Total_Other_mb= Users['Other DL'].sum() + Users['Other UL'].sum()

In [37]:
sessions_df = pd.concat([xDR_users,
                 session_duration,
                 Total_session_UL,
                 Total_session_DL,
                 Total_session_mb,
                 Total_Social_mb,
                 Total_Google_mb,
                 Total_Email_mb,
                 Total_Youtube_mb,
                 Total_Netflix_mb,
                 Total_Gaming_mb,
                 Total_Other_mb], axis="columns", sort=True)
sessions_df.head()

,IMSI,Dur. (ms),Total UL,Total DL,0,1,2,3,4,5,6,7
"204,047,108,489,451.00",1,"869,844.00","60,456,049.00","78,697,597.00","139,153,646.00","1,546,088.00","9,218,647.00","3,330,974.00","40,940,710.00","28,846,230.00","43,070,260.00","401,360,457.00"
"204,080,810,288,647.00",1,"877,385.00","37,295,915.00","194,828,056.00","232,123,971.00","715,224.00","10,438,660.00","1,520,771.00","11,959,905.00","26,592,300.00","178,048,738.00","470,526,473.00"
"208,200,101,016,140.00",1,"86,019.00","53,794,658.00","31,376,981.00","85,171,639.00","3,122,781.00","1,624,662.00","3,657,501.00","19,882,439.00","31,830,562.00","9,124,516.00","515,973,704.00"
"208,200,101,127,285.00",1,"86,254.00","33,583,272.00","392,918,313.00","426,501,585.00","2,577,104.00","13,811,478.00","3,855,734.00","25,657,632.00","27,785,852.00","344,105,897.00","309,610,741.00"
"208,200,101,148,045.00",2,"573,923.00","71,325,004.00","961,767,023.00","1,033,092,027.00","3,426,716.00","11,665,887.00","5,564,462.00","13,840,201.00","57,343,415.00","917,684,766.00","1,079,435,419.00"

In [38]:
scaled_sessions_df = (sessions_df-sessions_df.min())/(sessions_df.max()-sessions_df.min())
scaled_sessions_df.head()

,IMSI,Dur. (ms),Total UL,Total DL,0,1,2,3,4,5,6,7
"204,047,108,489,451.00",0.00,0.05,0.08,0.01,0.01,0.04,0.06,0.08,0.09,0.07,0.01,0.05
"204,080,810,288,647.00",0.00,0.05,0.05,0.02,0.02,0.02,0.07,0.04,0.03,0.07,0.02,0.06
"208,200,101,016,140.00",0.00,0.00,0.07,0.00,0.01,0.07,0.01,0.09,0.04,0.08,0.00,0.06
"208,200,101,127,285.00",0.00,0.00,0.04,0.05,0.04,0.06,0.09,0.09,0.06,0.07,0.04,0.04
"208,200,101,148,045.00",0.06,0.03,0.09,0.12,0.11,0.08,0.08,0.13,0.03,0.14,0.12,0.13

# Fix Outlier

In [39]:
# function to fix outliers
def fix_outlier(df, column):
    df[column] = np.where(df[column]> df[column].quantile(0.95), df[column].median(),df[column])
    
    return df[column]



for item in scaled_sessions_df.columns:
    scaled_sessions_df[item]=fix_outlier(scaled_sessions_df, item)
    
    
scaled_sessions_df.head()

,IMSI,Dur. (ms),Total UL,Total DL,0,1,2,3,4,5,6,7
"204,047,108,489,451.00",0.00,0.01,0.08,0.01,0.01,0.04,0.06,0.08,0.09,0.07,0.01,0.05
"204,080,810,288,647.00",0.00,0.01,0.05,0.02,0.02,0.02,0.07,0.04,0.03,0.07,0.02,0.06
"208,200,101,016,140.00",0.00,0.00,0.07,0.00,0.01,0.07,0.01,0.09,0.04,0.08,0.00,0.06
"208,200,101,127,285.00",0.00,0.00,0.04,0.05,0.04,0.06,0.09,0.09,0.06,0.07,0.04,0.04
"208,200,101,148,045.00",0.06,0.01,0.09,0.12,0.11,0.08,0.08,0.13,0.03,0.14,0.12,0.13

In [40]:
scaled_sessions_df.isnull().sum()

IMSI         0
Dur. (ms)    0
Total UL     0
Total DL     0
0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
dtype: int64

#  Exporting to csv file

In [64]:
df_clean.to_csv('../clean_csv_data/clean_df.csv')
sessions_df.to_csv('../clean_csv_data/sessions_df.csv')
scaled_sessions_df.to_csv('../clean_csv_data/scaled_sessions_df.csv')

In [49]:
df_clean['Total UL'].head()

1970-01-01 00:00:00.000000000   36,749,741.00
1970-01-01 00:00:00.000000001   53,800,391.00
1970-01-01 00:00:00.000000002   27,883,638.00
1970-01-01 00:00:00.000000003   43,324,218.00
1970-01-01 00:00:00.000000004   38,542,814.00
Name: Total UL, dtype: float64